#!/bin/bash

# set -x

script_path="$(readlink --canonicalize "$0")"
dir="$(dirname "$script_path")"

cd "$dir" || exit 1

# shellcheck disable=1090
source ".env/bin/activate"

poetry run aws-policy-generator
